### ISSUE TITLE
Failed to mount nodecg-io-irc extension: Cannot find module 'irc-colors'

### ISSUE THREAD

**Issue by SteffoSpieler** [codeoverflow-org/nodecg-io#325]
### Description

When starting nodecg-io/nodecg I get this error.

### How to reproduce

Can't give exact repoduction steps, as I just keep `git pull`ing the repository.

1. Start nodecg with `nodecg start`
2. See error.

### Error Log 
 
```
warn: [nodecg/lib/server/extensions] Failed to mount nodecg-io-irc extension:
Error: Cannot find module 'irc-colors'
Require stack:
- F:\NodeCG\nodecg\nodecg-io\services\nodecg-io-irc\node_modules\irc\lib\parse_message.js
- F:\NodeCG\nodecg\nodecg-io\services\nodecg-io-irc\node_modules\irc\lib\irc.js
- F:\NodeCG\nodecg\nodecg-io\services\nodecg-io-irc\extension\index.js
- F:\NodeCG\nodecg\lib\server\extensions.js
- F:\NodeCG\nodecg\lib\server\index.js
- F:\NodeCG\nodecg\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\dist\commands\start.js
- C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\dist\commands\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\dist\index.js
- C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\dist\bin\nodecg.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\NodeCG\nodecg\nodecg-io\services\nodecg-io-irc\node_modules\irc\lib\parse_message.js:1:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\NodeCG\nodecg\nodecg-io\services\nodecg-io-irc\node_modules\irc\lib\irc.js:27:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (F:\NodeCG\nodecg\nodecg-io\services\nodecg-io-irc\extension\index.js:5:15)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at _loadExtension (F:\NodeCG\nodecg\lib\server\extensions.js:103:21)
    at EventEmitter.module.exports.init (F:\NodeCG\nodecg\lib\server\extensions.js:45:6)
    at EventEmitter.module.exports.start (F:\NodeCG\nodecg\lib\server\index.js:310:19)
    at Object.<anonymous> (F:\NodeCG\nodecg\index.js:77:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Command.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\dist\commands\start.js:11:13)
    at Command.listener [as _actionHandler] (C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\node_modules\commander\index.js:426:31)
    at Command._parseCommand (C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\node_modules\commander\index.js:1002:14)
    at Command._dispatchSubcommand (C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\node_modules\commander\index.js:953:18)
    at Command._parseCommand (C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\node_modules\commander\index.js:970:12)
    at Command.parse (C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\node_modules\commander\index.js:801:10)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\dist\index.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\nodecg-cli\dist\bin\nodecg.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
info: [nodecg-io-midi-input] midi-input bundle started.

MidiInWinMM::initialize: no MIDI input devices currently available.
```

**Comment by daniel0611** [comment]
I've succesfully reproduced this and it also seems to affect streamelements, which too cannot be loaded due to some missing dependencies:

```
warn: [nodecg/lib/server/extensions] Failed to mount nodecg-io-streamelements extension:
Error: Cannot find module 'parseuri'
Require stack:
- /tmp/tmp.AZtUICPE9K/nodecg/nodecg-io/services/nodecg-io-streamelements/node_modules/socket.io-client/lib/url.js
- /tmp/tmp.AZtUICPE9K/nodecg/nodecg-io/services/nodecg-io-streamelements/node_modules/socket.io-client/lib/index.js
- /tmp/tmp.AZtUICPE9K/nodecg/nodecg-io/services/nodecg-io-streamelements/extension/StreamElements.js
- /tmp/tmp.AZtUICPE9K/nodecg/nodecg-io/services/nodecg-io-streamelements/extension/index.js
- /tmp/tmp.AZtUICPE9K/nodecg/lib/server/extensions.js
- /tmp/tmp.AZtUICPE9K/nodecg/lib/server/index.js
- /tmp/tmp.AZtUICPE9K/nodecg/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/tmp.AZtUICPE9K/nodecg/nodecg-io/services/nodecg-io-streamelements/node_modules/socket.io-client/lib/url.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/tmp.AZtUICPE9K/nodecg/nodecg-io/services/nodecg-io-streamelements/node_modules/socket.io-client/lib/index.js:6:11)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/tmp.AZtUICPE9K/nodecg/nodecg-io/services/nodecg-io-streamelements/extension/StreamElements.js:4:12)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/tmp.AZtUICPE9K/nodecg/nodecg-io/services/nodecg-io-streamelements/extension/index.js:5:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at _loadExtension (/tmp/tmp.AZtUICPE9K/nodecg/lib/server/extensions.js:103:13)
    at EventEmitter.module.exports.init (/tmp/tmp.AZtUICPE9K/nodecg/lib/server/extensions.js:45:6)
    at EventEmitter.module.exports.start (/tmp/tmp.AZtUICPE9K/nodecg/lib/server/index.js:310:19)
    at Object.<anonymous> (/tmp/tmp.AZtUICPE9K/nodecg/index.js:77:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

This only seems to affect the current `main` branch. When using the released `0.2.0` everything works fine.
I'll investigate further tomorrow.

**Comment by Tim-Tech-Dev** [comment]
Using the latest node 16 docker image and the nodecg-cli I get following errors:
```
node index.js
[…]
warn: [nodecg/lib/server/extensions] Failed to mount nodecg-io-irc extension:
Error: Cannot find module 'irc-colors'
Require stack:
- /nodecg/nodecg-io/services/nodecg-io-irc/node_modules/irc/lib/parse_message.js
- /nodecg/nodecg-io/services/nodecg-io-irc/node_modules/irc/lib/irc.js
- /nodecg/nodecg-io/services/nodecg-io-irc/extension/index.js
- /nodecg/lib/server/extensions.js
- /nodecg/lib/server/index.js
- /nodecg/index.js
[…]
info: [nodecg-io-midi-input] midi-input bundle started.
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

MidiInAlsa::initialize: error creating ALSA sequencer client object.

info: [nodecg-io-core] Service midi-input has been registered.
info: [nodecg/lib/server/extensions] Mounted nodecg-io-midi-input extension
info: [nodecg-io-midi-output] midi-output bundle started.
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory

MidiOutAlsa::initialize: error creating ALSA sequencer client object.

info: [nodecg-io-core] Service midi-output has been registered.
[…]
warn: [nodecg/lib/server/extensions] Failed to mount nodecg-io-streamelements extension:
Error: Cannot find module 'parseuri'
Require stack:
- /nodecg/nodecg-io/services/nodecg-io-streamelements/node_modules/socket.io-client/lib/url.js
- /nodecg/nodecg-io/services/nodecg-io-streamelements/node_modules/socket.io-client/lib/index.js
- /nodecg/nodecg-io/services/nodecg-io-streamelements/extension/StreamElements.js
- /nodecg/nodecg-io/services/nodecg-io-streamelements/extension/index.js
- /nodecg/lib/server/extensions.js
- /nodecg/lib/server/index.js
- /nodecg/index.js
```

Full log and setup:

https://gist.github.com/Tim-Tech-Dev/09437ce002d1be8ccdfa6ade2d81c8ee

**Comment by Tim-Tech-Dev** [comment]
Both the IRC and StreamElements warning do not appear tin the 0.2 release. And just suggesting from the files changed since then, I would suggest it may be an issue with the NPM lock file.

I just ran everything on the main branch again, but removing the package_lock.json before installing the packages. And it didn't report those two errors. So the package lock is the culprit.

https://gist.github.com/Tim-Tech-Dev/09437ce002d1be8ccdfa6ade2d81c8ee#file-nodecg-io-main_after_rm-log

**Comment by Tim-Tech-Dev** [comment]
May I suggest a ci run with nodecg installed to catch these errors in the future.

**Comment by daniel0611** [comment]
Yep, can verify that the lock file broke in ece876c6caac6278639a00184b5db74cdcb9c9f0 for some reason. Will regenerate and open a PR now.

Having a CI check to ensure NodeCG loads with nodecg-io installed would be definitely nice. NodeCG sadly doesn't error when loading of some bundles fail, so we would need to e.g. start nodecg, wait a couple of seconds for it to load and then analyze the logs unless you have a better idea.

**Comment by Tim-Tech-Dev** [comment]
Maybe write a bundle, which will require all our bundles and crash the process if one isn't present.

**Comment by daniel0611** [comment]
Great idea! We cannot crash it, as it is not going to be loaded if any bundle is missing. However we can search the logs for the `Mounted <bundle name> extension` message that NodeCG prints when a bundle gets loaded and ensure that is present for this bundle.

**Comment by daniel0611** [comment]
> I just ran everything on the main branch again, but removing the package-lock.json before installing the packages. And it didn't report those two errors. So the package lock is the culprit.
> 
> https://gist.github.com/Tim-Tech-Dev/09437ce002d1be8ccdfa6ade2d81c8ee#file-nodecg-io-main_after_rm-log

I think something is wrong with my setup. Even after deleting the lock file and generating it breaks, lol. Let me try this in a clean setup...

**Comment by Tim-Tech-Dev** [comment]
> Great idea! We cannot crash it, as it is not going to be loaded if any bundle is missing. However we can search the logs for the `Mounted <bundle name> extension` message that NodeCG prints when a bundle gets loaded and ensure that is present for this bundle.

I would make a PR
